---
sidebar: sidebar 
permalink: concepts/choose-class-and-size.html 
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers 
summary: Le centre de contrôle Astra prend uniquement en charge les classes de stockage Trident basées sur le stockage ONTAP. Comprenez comment la classe de stockage et la taille de volume persistant peuvent vous aider à atteindre vos objectifs de performance. 
---
= Classes de stockage et taille de volume persistant
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center prend en charge ONTAP en tant que système de stockage back-end. Découvrez comment la classe de stockage et la taille des volumes persistants peuvent vous aider à atteindre vos objectifs de performance.



== Présentation

Astra Control Center prend uniquement en charge les classes de stockage Trident qui sont à l'heure actuelle basées sur le stockage ONTAP. Le centre de contrôle Astra détecte et utilise les ressources déjà déployées, notamment ONTAP, Trident et des classes de stockage associées.


NOTE: Les classes de stockage Trident doivent être préconfigurées en dehors du centre de contrôle Astra.



== Classes de stockage

Lorsque vous ajoutez des clusters à Astra Control Center, vous êtes invité à choisir l'une des classes de stockage précédemment découvertes pour les volumes persistants. Les niveaux de service des classes de stockage sont conçus pour différents besoins en capacité et bande passante. Ces classes de stockage découvertes sont admissibles au Centre de contrôle Astra.



== Taille et performance du volume persistant

Consultez les informations de Trident pour comparer les coûts et obtenir des exemples qui vous aideront à mieux comprendre comment allier un niveau de service à une taille de volume pour atteindre vos objectifs de performance.



== Trouvez plus d'informations

* https://netapp-trident.readthedocs.io/en/stable-v21.01/dag/kubernetes/storage_configuration_trident.html["Documentation Trident sur la configuration du stockage"^]

