---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: 'Pour installer Astra Control Center après avoir défini certaines conditions préalables à l"environnement, téléchargez le pack et installez-le en suivant les étapes décrites.' 
---
= Poser le centre de contrôle Astra
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Pour installer le centre de contrôle Astra, procédez comme suit :

* <<Poser le centre de contrôle Astra>>
* <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra>>




== Poser le centre de contrôle Astra

Pour installer Astra Control Center, téléchargez le bundle d'installation sur le site de support NetApp et exécutez une série de commandes pour installer l'opérateur d'Astra Control Center et le centre de contrôle d'Astra dans votre environnement. Vous pouvez utiliser cette procédure pour installer Astra Control Center dans des environnements connectés à Internet ou équipés d'un filtre à air.

.Ce dont vous avez besoin
* link:requirements.html["Avant de commencer l'installation, préparez votre environnement pour le déploiement d'Astra Control Center"].
* Depuis votre cluster OpenShift, assurez-vous que tous les opérateurs de clusters sont en état sain (`available` est `true`) :
+
[listing]
----
oc get clusteroperators
----
* Depuis votre cluster OpenShift, assurez-vous que tous les services d'API sont en état sain (`available` est `true`) :
+
[listing]
----
oc get apiservices
----


.Description de la tâche
La procédure d'installation d'Astra Control Center est la suivante :

* Installe les composants Astra dans le `netapp-acc` (ou espace de nom personnalisé).
* Crée un compte par défaut.
* Définit une adresse e-mail d'utilisateur administratif par défaut et un mot de passe unique par défaut de `ACC-<UUID_of_installation>` Pour cet exemple de centre de contrôle Astra. Ce rôle est attribué à cet utilisateur dans le système et est nécessaire pour la première connexion à l'interface utilisateur.
* Vous aide à déterminer que toutes les POD Astra Control Center sont en cours d'exécution.
* Installe l'interface utilisateur Astra.



NOTE: Les commandes Podman peuvent être utilisées à la place des commandes Docker si vous utilisez le référentiel Podman de Red Hat.

.Étapes
. Téléchargez le pack Astra Control Center (`astra-control-center-[version].tar.gz`) du https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de support NetApp"^].
. Téléchargez le code postal des certificats et clés Astra Control Center à l'adresse https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de support NetApp"^].
. (Facultatif) utilisez la commande suivante pour vérifier la signature du pack :
+
[listing]
----
openssl dgst -sha256 -verify astra-control-center[version].pub -signature <astra-control-center[version].sig astra-control-center[version].tar.gz
----
. Extraire les images :
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----
. Passez au répertoire Astra.
+
[listing]
----
cd astra-control-center-[version]
----
. Ajoutez les fichiers du répertoire d'images de l'Astra Control Center à votre registre local.
+

NOTE: Voir un exemple de script pour le chargement automatique des images ci-dessous.

+
.. Connectez-vous à votre registre Docker :
+
[listing]
----
docker login [Docker_registry_path]
----
.. Chargez les images dans Docker.
.. Marquez les images.
.. Envoyez les images dans votre registre local.


+
[listing]
----
export REGISTRY=[Docker_registry_path]
for astraImageFile in $(ls images/*.tar) ; do
  # Load to local cache. And store the name of the loaded image trimming the 'Loaded images: '
  astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
  astraImage=$(echo ${astraImage} | sed 's!localhost/!!')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/${astraImage}
  # Push to the local repo.
  docker push ${REGISTRY}/${astraImage}
done
----
. (Pour les registres avec des exigences d'authentification uniquement) si vous utilisez un registre qui nécessite une authentification, vous devez procéder comme suit :
+
.. Créer le `netapp-acc-operator` espace de noms :
+
[listing]
----
kubectl create ns netapp-acc-operator
----
+
Réponse :

+
[listing]
----
namespace/netapp-acc-operator created
----
.. Créez un secret pour le `netapp-acc-operator` espace de noms. Ajoutez des informations sur Docker et exécutez la commande suivante :
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Exemple de réponse :

+
[listing]
----
secret/astra-registry-cred created
----
.. Créer le `netapp-acc` (ou espace de nom personnalisé).
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Exemple de réponse :

+
[listing]
----
namespace/netapp-acc created
----
.. Créez un secret pour le `netapp-acc` (ou espace de nom personnalisé). Ajoutez des informations sur Docker et exécutez la commande suivante :
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom] --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Réponse

+
[listing]
----
secret/astra-registry-cred created
----


. Modifiez le yaml de déploiement de l'opérateur Astra Control Center (`astra_control_center_operator_deploy.yaml`) pour faire référence à votre registre local et à votre secret.
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. Si vous utilisez un registre qui nécessite une authentification, remplacez la ligne par défaut de `imagePullSecrets: []` avec les éléments suivants :
+
[listing]
----
imagePullSecrets:
- name: astra-registry-cred
----
.. Changer `[Docker_registry_path]` pour le `kube-rbac-prox` image dans le chemin du registre où vous avez poussé les images à l'étape précédente.
.. Changer `[Docker_registry_path]` pour le `acc-operator-controller-manager` image dans le chemin du registre où vous avez poussé les images à l'étape précédente.


+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [Docker_registry_path]/kube-rbac-proxy:v0.5.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [Docker_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----
. Modifiez le fichier de ressources personnalisées (CR) Astra Control Center (`astra_control_center_min.yaml`) :
+
[listing]
----
vim astra_control_center_min.yaml
----
+

NOTE: Si d'autres personnalisations sont nécessaires pour votre environnement, vous pouvez l'utiliser `astra_control_center.yaml` En tant que CR alternatif. `astra_control_center_min.yaml` Est le CR par défaut et convient à la plupart des installations.

+

NOTE: Les propriétés configurées par le CR ne peuvent pas être modifiées après le déploiement initial du centre de contrôle Astra.

+
.. Changer `[Docker_registry_path]` vers le chemin du registre où vous avez poussé les images à l'étape précédente.
.. Modifiez le `accountName` chaîne du nom que vous souhaitez associer au compte.
.. Modifiez le `astraAddress` Chaîne du FQDN que vous souhaitez utiliser dans votre navigateur pour accéder à Astra. Ne pas utiliser `http://` ou `https://` dans l'adresse. Copier ce FQDN pour l'utiliser dans un <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra,plus tard>>.
.. Modifiez le `email` chaîne à l'adresse d'administrateur initiale par défaut. Copiez cette adresse e-mail pour l'utiliser dans un <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra,plus tard>>.
.. Changer `enrolled` Pour AutoSupport à `false` pour les sites sans connexion internet ou sans conservation `true` pour les sites connectés.
.. (Facultatif) Ajouter un prénom `firstName` et nom `lastName` de l'utilisateur associé au compte. Vous pouvez effectuer cette étape maintenant ou plus tard dans l'interface utilisateur.
.. (Facultatif) modifiez le `storageClass` Valeur ajoutée pour une autre ressource de stockage Trident si votre installation l'exige.
.. Si vous n'utilisez pas de registre nécessitant une autorisation, supprimez le `secret` ligne.


+
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[Docker_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
----
. Poser le conducteur du centre de commande Astra :
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Exemple de réponse :

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. Si vous ne l'avez pas déjà fait dans une étape précédente, créez le `netapp-acc` (ou personnalisée) espace de noms :
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Exemple de réponse :

+
[listing]
----
namespace/netapp-acc created
----
. Exécutez le correctif suivant pour corriger le problème link:https://docs.netapp.com/us-en/astra-control-center/release-notes/known-issues.html#Incorrect-ClusterRoleBinding-created-by-Astra-Control-Center-CRD-during-installation["liaison de rôle de cluster"].
. Poser le centre de contrôle Astra dans le `netapp-acc` (ou votre espace de noms personnalisé) :
+
[listing]
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom]
----
+
Exemple de réponse :

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----
. Vérifiez que tous les composants du système sont correctement installés.
+
[listing]
----
kubectl get pods -n [netapp-acc or custom]
----
+
Chaque pod doit avoir un statut de `Running`. Le déploiement des modules du système peut prendre plusieurs minutes.

+
Exemple de réponse :

+
[listing]
----
NAME                                         READY   STATUS    RESTARTS   AGE
acc-helm-repo-5fdfff786f-gkv6z               1/1     Running   0          4m58s
activity-649f869bf7-jn5gs                    1/1     Running   0          3m14s
asup-79846b5fdc-s9s97                        1/1     Running   0          3m10s
authentication-84c78f5cf4-qhx9t              1/1     Running   0          118s
billing-9b8496787-v8rzv                      1/1     Running   0          2m54s
bucketservice-5fb876d9d5-wkfvz               1/1     Running   0          3m26s
cloud-extension-f9f4f59c6-dz6s6              1/1     Running   0          3m
cloud-insights-service-5676b8c6d4-6q7lv      1/1     Running   0          2m52s
composite-compute-7dcc9c6d6c-lxdr6           1/1     Running   0          2m50s
composite-volume-74dbfd7577-cd42b            1/1     Running   0          3m2s
credentials-75dbf46f9d-5qm2b                 1/1     Running   0          3m32s
entitlement-6cf875cb48-gkvhp                 1/1     Running   0          3m12s
features-74fd97bb46-vss2n                    1/1     Running   0          3m6s
fluent-bit-ds-2g9jb                          1/1     Running   0          113s
fluent-bit-ds-5tg5h                          1/1     Running   0          113s
fluent-bit-ds-qfxb8                          1/1     Running   0          113s
graphql-server-7769f98b86-p4qrv              1/1     Running   0          90s
identity-566c566cd5-ntfj6                    1/1     Running   0          3m16s
influxdb2-0                                  1/1     Running   0          4m43s
krakend-5cb8d56978-44q66                     1/1     Running   0          93s
license-66cbbc6f48-27kgf                     1/1     Running   0          3m4s
login-ui-584f7fd84b-dmdrp                    1/1     Running   0          87s
loki-0                                       1/1     Running   0          4m44s
metrics-ingestion-service-6dcfddf45f-mhnvh   1/1     Running   0          3m8s
monitoring-operator-78d67b4d4-nxs6v          2/2     Running   0          116s
nats-0                                       1/1     Running   0          4m40s
nats-1                                       1/1     Running   0          4m26s
nats-2                                       1/1     Running   0          4m15s
nautilus-9b664bc55-rn9t8                     1/1     Running   0          2m56s
openapi-dc5ddfb7d-6q8vh                      1/1     Running   0          3m20s
polaris-consul-consul-5tjs7                  1/1     Running   0          4m43s
polaris-consul-consul-5wbnx                  1/1     Running   0          4m43s
polaris-consul-consul-bfvl7                  1/1     Running   0          4m43s
polaris-consul-consul-server-0               1/1     Running   0          4m43s
polaris-consul-consul-server-1               1/1     Running   0          4m43s
polaris-consul-consul-server-2               1/1     Running   0          4m43s
polaris-mongodb-0                            2/2     Running   0          4m49s
polaris-mongodb-1                            2/2     Running   0          4m22s
polaris-mongodb-arbiter-0                    1/1     Running   0          4m49s
polaris-ui-6648875998-75d98                  1/1     Running   0          92s
polaris-vault-0                              1/1     Running   0          4m41s
polaris-vault-1                              1/1     Running   0          4m41s
polaris-vault-2                              1/1     Running   0          4m41s
storage-backend-metrics-69546f4fc8-m7lfj     1/1     Running   0          3m22s
storage-provider-5d46f755b-qfv89             1/1     Running   0          3m30s
support-5dc579865c-z4pwq                     1/1     Running   0          3m18s
telegraf-ds-4452f                            1/1     Running   0          113s
telegraf-ds-gnqxl                            1/1     Running   0          113s
telegraf-ds-jhw74                            1/1     Running   0          113s
telegraf-rs-gg6m4                            1/1     Running   0          113s
telemetry-service-6dcc875f98-zft26           1/1     Running   0          3m24s
tenancy-7f7f77f699-q7l6w                     1/1     Running   0          3m28s
traefik-769d846f9b-c9crt                     1/1     Running   0          83s
traefik-769d846f9b-l9n4k                     1/1     Running   0          67s
trident-svc-8649c8bfc5-pdj79                 1/1     Running   0          2m57s
vault-controller-745879f98b-49c5v            1/1     Running   0          4m51s
----
. (Facultatif) pour vous assurer que l'installation est terminée, vous pouvez regarder le `acc-operator` journaux utilisant la commande suivante.
+
[listing]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
. Lorsque tous les pods s'exécutent, vérifiez que l'installation est réussie en récupérant l'instance AstrakControlCenter installée par l'opérateur ACC.
+
[listing]
----
kubectl get acc -o yaml -n netapp-acc
----
. Vérifier le `status.deploymentState` dans le champ de réponse pour le `Deployed` valeur. Si le déploiement a échoué, un message d'erreur s'affiche à la place.
+

NOTE: Vous utiliserez le `uuid` à l'étape suivante.

+
[listing, subs="+quotes"]
----
apiVersion: v1
items:
- apiVersion: astra.netapp.io/v1
  kind: AstraControlCenter
  metadata:
    creationTimestamp: "2021-07-28T21:36:49Z"
    finalizers:
    - astracontrolcenter.netapp.io/finalizer
   generation: 1
    name: astra
    namespace: netapp-acc
    resourceVersion: "27797604"
    selfLink: /apis/astra.netapp.io/v1/namespaces/netapp-acc/astracontrolcenters/astra
    uid: 61cd8b65-047b-431a-ba35-510afcb845f1
  spec:
    accountName: Example
    astraAddress: astra.example.com
    astraResourcesScaler: "Off"
    astraVersion: 21.08.52
    autoSupport:
      enrolled: false
    email: admin@example.com
    firstName: SRE
    lastName: Admin
    imageRegistry:
      name: registry_name/astra
  status:
    certManager: deploy
    *deploymentState: Deployed*
    observedGeneration: 1
    observedVersion: 21.08.52
    postInstall: Complete
    *uuid: c49008a5-4ef1-4c5d-a53e-830daf994116*
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
----
. Pour obtenir le mot de passe unique que vous utiliserez lorsque vous vous connecterez à Astra Control Center, copiez le `status.uuid` valeur de la réponse à l'étape précédente. Le mot de passe est `ACC-` Suivi de la valeur UUID (`ACC-[UUID]` ou, dans cet exemple, `ACC-c49008a5-4ef1-4c5d-a53e-830daf994116`).




== Connectez-vous à l'interface utilisateur du centre de contrôle Astra

Après avoir installé ACC, vous modifierez le mot de passe de l'administrateur par défaut et vous connecterez au tableau de bord de l'interface utilisateur ACC.

.Étapes
. Dans un navigateur, entrez le FQDN que vous avez utilisé dans le `astraAddress` dans le  `astra_control_center_min.yaml` CR quand <<Poser le centre de contrôle Astra,Vous avez installé ACC>>.
. Acceptez les certificats auto-signés lorsque vous y êtes invité.
+

NOTE: Vous pouvez créer un certificat personnalisé après la connexion.

. Dans la page de connexion à Astra Control Center, entrez la valeur que vous avez utilisée `email` dans `astra_control_center_min.yaml` CR quand <<Poser le centre de contrôle Astra,Vous avez installé ACC>>, suivi du mot de passe à usage unique (`ACC-[UUID]`).
+

NOTE: Si vous saisissez trois fois un mot de passe incorrect, le compte admin est verrouillé pendant 15 minutes.

. Sélectionnez *connexion*.
. Modifiez le mot de passe lorsque vous y êtes invité.
+

NOTE: Si c'est votre premier login et que vous oubliez le mot de passe et qu'aucun autre compte utilisateur administratif n'a encore été créé, contactez le support NetApp pour obtenir de l'aide pour la récupération de mot de passe.

. (Facultatif) supprimez le certificat TLS auto-signé existant et remplacez-le par un link:../get-started/add-custom-tls-certificate.html["Certificat TLS personnalisé signé par une autorité de certification"].




== Dépanner l'installation

Si l'un des services est dans `Error` état, vous pouvez inspecter les journaux. Rechercher les codes de réponse API dans la plage 400 à 500. Ceux-ci indiquent l'endroit où un échec s'est produit.

.Étapes
. Pour inspecter les journaux de l'opérateur de l'Astra Control Center, entrez ce qui suit :
+
[listing]
----
kubectl logs --follow -n netapp-acc-operator $(kubectl get pods -n netapp-acc-operator -o name)  -c manager
----




== Et la suite

Terminez le déploiement en effectuant le processus link:setup_overview.html["tâches de configuration"].
