---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: Commencez à utiliser Astra Control Center en vérifiant la prise en charge de vos clusters Kubernetes, de vos applications et de votre navigateur Web. 
---
= Exigences du centre de contrôle Astra
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Commencez par vérifier le support de vos clusters Kubernetes, applications, licences et navigateurs Web.



== Configuration générale du cluster Kubernetes

Un cluster Kubernetes doit satisfaire aux exigences générales suivantes pour que vous puissiez la découvrir et la gérer à partir d'Astra Control Center.

* *Registre d'images*: Vous devez avoir un registre d'images privé Docker existant à laquelle vous pouvez pousser les images de construction d'Astra Control Center. Vous devez avoir l'URL du registre d'images où vous allez télécharger les images, et vous devez avoir marqué les images pour le registre du conteneur privé.
* *Configuration du stockage ONTAP/Trident* : Astra Control Center requiert que la version 21.01 ou 21.04 de Trident soit déjà installée et configurée pour fonctionner avec NetApp ONTAP version 9.5 ou plus récente en tant que système back-end. Avec Astra Control Center, il est nécessaire de créer une classe de stockage et de la définir comme classe de stockage par défaut. Le centre de contrôle Astra prend en charge les pilotes ONTAP suivants fournis par Trident :
+
** ontap-nas
** ontap-nas-flexgroup
** ontap-san
** ontap-san-économie




Si vous prévoyez de gérer le cluster Kubernetes à partir d'Astra Control Center et d'utiliser le cluster pour héberger l'installation d'Astra Control Center, le cluster doit satisfaire les exigences supplémentaires suivantes :

* La version la plus récente de Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html["composant de snapshot-controller"^] est installé
* Un Trident https://netapp-trident.readthedocs.io/en/latest/kubernetes/concepts/objects.html?highlight=VolumeSnapshotClass#kubernetes-volumesnapshotclass-objects["objet volumesnapshotclass"^] a été défini par un administrateur
* Une classe de stockage Kubernetes par défaut existe sur le cluster
* Au moins une classe de stockage est configurée pour utiliser Trident
* Méthode de pointage du FQDN de Astra Control Center vers l'adresse IP externe du service Astra Control Center




=== Clusters OpenShift

L'Astra Control Center requiert un cluster Red Hat OpenShift Container Platform 4.6.8 ou 4.7 qui possède des classes de stockage Trident basées sur ONTAP 9.5 ou version ultérieure. Il inclut les attributs suivants :

* Au moins 300 Go de capacité de stockage ONTAP disponible
* 3 nœuds de contrôleur avec 4 cœurs de CPU, 16 Go de RAM et 120 Go de stockage disponibles chacun
* 3 nœuds workers avec au moins 12 cœurs CPU, 32 Go de RAM et 50 Go de stockage disponibles chacun
* Kubernetes version 1.19 ou 1.20
* Type de service « LoadBalancer » disponible pour le trafic d'entrée qui sera envoyé aux services du cluster OpenShift
* Méthode permettant de pointer le FQDN de Astra Control Center vers l'adresse IP à charge équilibrée



NOTE: Ces exigences minimales supposent que Astra Control Center est la seule application qui s'exécute sur le cluster OpenShift. Si le cluster exécute des applications supplémentaires, vous devez ajuster ces exigences minimales en conséquence.

Assurez-vous que votre cluster répond au minimum requis et que vous suivez les bonnes pratiques de Kubernetes de sorte qu'Astra Control Center est hautement disponible dans votre cluster Kubernetes.


NOTE: OpenShift 4.8 n'est pas pris en charge.

[NOTE]
====
Lors du clonage d'applications, Astra Control Center doit permettre à OpenShift de monter des volumes et de modifier la propriété des fichiers. Par conséquent, ONTAP doit être configuré pour permettre aux opérations de volume d'être correctement effectuées à l'aide des commandes suivantes :

. `export-policy rule modify -vserver svm0 -policyname default -ruleindex 1 -superuser sys`
. `export-policy rule modify -policyname default -ruleindex 1 -anon 65534`


====

NOTE: Si vous prévoyez d'ajouter un second cluster OpenShift 4.6 ou 4.7 en tant que ressource de calcul gérée, vous devez vous assurer que la fonctionnalité Snapshot des volumes Trident est activée. Voir le Trident officiel https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/volumes/snapshots.html?highlight=volumesnapshot#on-demand-volume-snapshots["instructions"^] Pour activer et tester des snapshots de volume avec Trident.



=== Besoins en termes de gestion des applications

Astra Control Center a les exigences suivantes en matière de gestion des applications :

* *Licensing*: Vous avez besoin d'une licence Astra Control Center pour gérer les applications à l'aide d'Astra Control Center.
* *Helm 3* : si vous utilisez Helm pour déployer des applications, Astra Control Center requiert Helm version 3. La gestion et le clonage des applications déployées avec Helm 3 (ou mises à niveau de Helm 2 à Helm 3) sont entièrement pris en charge. Les applications déployées avec Helm 2 ne sont pas prises en charge.
* *Operator Management*: Astra Control Center ne prend pas en charge les applications déployées avec les opérateurs Operator Lifecycle Manager (OLM) ou les opérateurs cluster-scoped.




== Accès à Internet

Vous devez déterminer si vous avez un accès externe à Internet. Par ailleurs, certaines fonctionnalités sont limitées, comme la réception de données de surveillance et de metrics depuis NetApp Cloud Insights ou l'envoi de packs de support vers le site de support NetApp.



== Licence

Astra Control Center requiert une licence Astra Control Center pour bénéficier de toutes les fonctionnalités. Obtenez une licence d'évaluation ou une licence complète auprès de NetApp. Sans licence, vous ne pourrez pas :

* Définir des applications personnalisées
* Créer des snapshots ou des clones d'applications existantes
* Configuration des règles de protection des données


Si vous voulez essayer Astra Control Center, vous pouvez link:setup_overview.html#add-a-full-or-evaluation-license["utilisez une licence d'essai gratuite de 90 jours"].



== Type de service « LoadBalancer » pour les clusters Kubernetes sur site

Astra Control Center utilise un service de type "LoadBalancer" (svc/trafik dans l'espace de noms du Centre de contrôle Astra), et exige qu'il se voit attribuer une adresse IP externe accessible. Pour les clusters OpenShift sur site, vous pouvez utiliser https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["MetalLB"^] Pour attribuer automatiquement une adresse IP externe au service. Dans la configuration du serveur DNS interne, pointez le nom DNS choisi pour Astra Control Center vers l'adresse IP à équilibrage de charge.



== Configuration réseau requise

Le cluster qui héberge Astra Control Center communique avec les ports TCP suivants. Veillez à ce que ces ports soient autorisés par le biais de pare-feu et configurez des pare-feu pour autoriser tout trafic de sortie HTTPS provenant du réseau Astra. Certains ports nécessitent une connectivité entre le cluster hébergeant le centre de contrôle Astra et chaque cluster géré (le cas échéant).

|===
| Solution NetApp | Port | Protocole | Direction | Objectif 


| Centre de contrôle Astra | 443 | HTTPS | Entrée | Accès à l'interface utilisateur/à l'API : assurez-vous que ce port est ouvert à la fois entre le cluster hébergeant Astra Control Center et chaque cluster géré 


| Centre de contrôle Astra | 9090 | HTTPS  a| 
* Entrée (vers le cluster hébergeant le centre de contrôle Astra)
* Sortie (port aléatoire de l'adresse IP de nœud de chaque nœud worker de chaque cluster géré)

| Données de mesure destinées aux consommateurs de metrics : assurez-vous que chaque cluster géré peut accéder à ce port sur le cluster hébergeant Astra Control Center 


| Trident | 34571 | HTTPS | Entrée | Communication avec le pod de nœuds 


| Trident | 9220 | HTTP | Entrée | Terminal de metrics 
|===


== Navigateurs Web pris en charge

Astra Control Center prend en charge les versions récentes de Firefox, Safari et Chrome avec une résolution minimale de 1280 x 720.



== Et la suite

Afficher le link:quick-start.html["démarrage rapide"] présentation.
