---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 'Les problèmes connus identifient les problèmes susceptibles de vous empêcher d"utiliser cette version du produit avec succès.' 
---
= Problèmes connus avec cette version
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


Les problèmes connus identifient les problèmes susceptibles de vous empêcher d'utiliser cette version du produit avec succès.

Les problèmes connus suivants ont une incidence sur la version actuelle :

*  ClusterRoleBinding created by Astra Control Center CRD during installation
*  with user-defined label goes into "removed" state
*  to stop running app backup
*  or clone fails for apps using PVCs with decimal units in Astra Control Center
*  Control Center UI slow to show changes to app resources such as persistent volume changes
*  app restore from backup Trident creates a larger PV than the original PV
*  performance impacted by large persistent volumes
*  clones fail using a specific version of PostgreSQL
*  clones fail when using Service Account level OCP Security Context Constraints (SCC)
*  buckets in Astra Control Center do not report available capacity
*  buckets between instances of Astra Control Center causes failures
*  a bucket provider type with credentials for another type causes data protection failures
*  and snapshots might not be retained during removal of an Astra Control Center instance
*  backups are retained as part of scheduled backup
* link:known-issues.html#clone-operation-cant-use-other-buckets-besides-the-default["L'opération de clonage ne peut pas utiliser d'autres compartiments par défaut"]
*  a cluster with Astra Control Center fails when default kubeconfig file contains more than one context
* link:known-issues.html#cant-determine-asup-tar-bundle-status-in-scaled-environment["Impossible de déterminer l'état du bundle tar ASUP dans l'environnement mis à l'échelle"]
*  of Astra Control Center fails to clean up the monitoring-operator pod on the managed cluster
*  of Astra Control Center fails to clean up Traefik CRDs
*  collection stuck in a generating or uploading state




== ClusterRoleBinding incorrect créé par le CRD Astra Control Center lors de l'installation

Appliquez le correctif suivant à tous les clusters Kubernetes où la version 21.08.65 de ACC a été déployée. Il doit également être appliqué si l'ACC est redéployé.

Pour résoudre ce problème :

. Remplacement `ACC_NAMESPACE` dans le script ci-dessous avec l'espace de nom que vous avez utilisé link:../get-started/install_acc.html#install-astra-control-center["Déployez Astra Control Center"].
+
[source, cli]
----
cat <<EOF | kubectl apply -f –
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acc-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: netapp-acc-operator
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ACC_NAMESPACE
EOF
----
. Exécutez le script.


Le correctif supprime les deux sujets suivants de `ClusterRoleBinding: "acc-operator-manager-rolebinding"`

[listing]
----
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: ""
  kind: Group
  name: system:serviceaccounts
----


== L'application avec étiquette définie par l'utilisateur passe à l'état « supprimé »

Si vous définissez une application avec une étiquette k8s inexistante, Astra Control Center crée, gère, puis supprime immédiatement l'application. Pour éviter cela, ajoutez l'étiquette k8s aux pods et aux ressources après la gestion de l'application par Astra Control Center.



== Impossible d'arrêter la sauvegarde de l'application en cours d'exécution

Il est impossible d'arrêter une sauvegarde en cours d'exécution. Si vous devez supprimer la sauvegarde, attendez qu'elle soit terminée, puis suivez les instructions de la section link:../use/protect-apps.html#delete-backups["Supprimer les sauvegardes"]. Pour supprimer une sauvegarde ayant échoué, utilisez le link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["API Astra"^].



== La sauvegarde ou le clonage échoue pour les applications utilisant des ESV avec des unités décimales dans Astra Control Center

Les volumes créés avec des unités décimales échouent à l'aide du processus de sauvegarde ou de clonage Astra Control Center. Voir la link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Backup_or_clone_may_fail_for_applications_using_PVCs_with_decimal_units_in_Astra_Control_Center["article de la base de connaissances"] pour en savoir plus.



== L'interface utilisateur d'Astra Control Center est lente à afficher les modifications apportées aux ressources d'application, telles que les changements de volume persistant

Après une opération de protection des données (clonage, sauvegarde, restauration) et après le redimensionnement du volume persistant, il y a vingt minutes de retard avant que la nouvelle taille du volume ne s'affiche dans l'interface utilisateur. Ce délai dans l'interface utilisateur peut également survenir lors de l'ajout ou de la modification de ressources d'application. Dans ce cas, une opération de protection des données fonctionne avec succès en quelques minutes et vous pouvez utiliser le logiciel de gestion pour le système back-end pour confirmer la modification de la taille du volume.



== Lors de la restauration d'applications à partir de la sauvegarde, Trident crée un volume persistant plus important que le volume persistant d'origine

Si vous redimensionnez un volume persistant après avoir créé une sauvegarde puis restauré à partir de cette sauvegarde, la taille du volume persistant correspond à la nouvelle taille du volume persistant, et non à la taille de la sauvegarde.



== Performances de clones affectées par de grands volumes persistants

Les clones de volumes persistants de très grande taille et consommés par intermittence peuvent être lents, selon l'accès du cluster au magasin d'objets. Si le clone est suspendu et qu'aucune donnée n'a été copiée pendant plus de 30 minutes, Astra Control met fin à l'action de clonage.



== Les clones d'applications échouent à l'aide d'une version spécifique de PostgreSQL

Les clones d'applications au sein du même cluster échouent systématiquement avec le graphique Bitnami PostgreSQL 11.5.0. Pour effectuer un clonage réussi, utilisez une version antérieure ou ultérieure du graphique.



== Les clones d'application échouent lors de l'utilisation des contraintes de contexte de sécurité OCP au niveau du compte de service (SCC)

Un clone d'application peut échouer si les contraintes de contexte de sécurité d'origine sont configurées au niveau du compte de service au sein de l'espace de noms sur le cluster OCP. Lorsque le clone de l'application échoue, il apparaît dans la zone applications gérées du Centre de contrôle Astra avec l'état `Removed`. Voir la https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["article de la base de connaissances"] pour en savoir plus.



== Les compartiments S3 du centre de contrôle Astra n'indiquent pas la capacité disponible

Avant de sauvegarder ou de cloner des applications gérées par Astra Control Center, vérifiez les informations de compartiment dans le système de gestion ONTAP ou StorageGRID.



== La réutilisation de compartiments entre des instances d'Astra Control Center provoque des défaillances

Si vous tentez de réutiliser un compartiment utilisé par une autre installation ou une installation précédente d'Astra Control Center, la sauvegarde et la restauration échoueront. Vous devez utiliser un autre godet ou nettoyer complètement le godet utilisé précédemment. Vous ne pouvez pas partager de compartiments entre les instances d'Astra Control Center.



== La sélection d'un type de compartiment avec des identifiants d'un autre type entraîne des défaillances de protection des données

Lorsque vous ajoutez un compartiment, sélectionnez le type de fournisseur de compartiment approprié avec les identifiants appropriés pour ce fournisseur. Par exemple, l'interface utilisateur accepte NetApp ONTAP S3 comme type avec les identifiants StorageGRID. Toutefois, toutes les futures sauvegardes et restaurations des applications à l'aide de ce compartiment échoueront.



== Il est possible que les sauvegardes et les snapshots ne soient pas conservés lors du retrait d'une instance Astra Control Center

Si vous disposez d'une licence d'évaluation, veillez à stocker votre identifiant de compte afin d'éviter toute perte de données en cas d'échec du Centre de contrôle Astra si vous n'envoyez pas d'ASUP.



== Les sauvegardes supplémentaires sont conservées dans le cadre d'une sauvegarde planifiée

Parfois, une ou plusieurs sauvegardes dans Astra Control Center sont conservées au-delà du numéro spécifié pour être conservées dans le programme de sauvegarde. Ces sauvegardes supplémentaires doivent être supprimées dans le cadre d'une sauvegarde planifiée, mais elles ne sont pas supprimées et bloquées dans un `pending` état. Pour résoudre le problème, https://docs.netapp.com/us-en/astra-automation-2108/workflows/wf_delete_backup.html["forcer la suppression"] les sauvegardes supplémentaires.



== L'opération de clonage ne peut pas utiliser d'autres compartiments en plus de la valeur par défaut

Lors d'une sauvegarde ou d'une restauration d'application, vous pouvez éventuellement spécifier un ID de compartiment. Cependant, une opération de clonage d'application utilise toujours le compartiment par défaut défini. Il n'existe aucune option pour modifier les compartiments d'un clone. Si vous souhaitez contrôler le godet utilisé, vous pouvez l'un des deux link:../use/manage-buckets.html#edit-a-bucket["modifiez les paramètres par défaut du compartiment"] ou faites un link:../use/protect-apps.html#create-a-backup["sauvegarde"] suivi d'un link:../use/restore-apps.html["restaurer"] séparément.



== La gestion d'un cluster avec Astra Control Center échoue lorsque le fichier kubeconfig par défaut contient plusieurs contextes

Vous ne pouvez pas utiliser un kubeconfig avec plus d'un cluster et un contexte. Voir la link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["article de la base de connaissances"] pour en savoir plus.



== Impossible de déterminer l'état du bundle tar ASUP dans l'environnement mis à l'échelle

Lors de la collecte ASUP, l'état du bundle dans l'interface utilisateur est signalé comme étant l'un ou l'autre `collecting` ou `done`. La collecte peut prendre jusqu'à une heure pour les grands environnements. Lors du téléchargement ASUP, la vitesse de transfert du fichier réseau pour le bundle peut être insuffisante et le téléchargement peut s'interrompre au bout de 15 minutes sans indication dans l'interface utilisateur. Les problèmes de téléchargement dépendent de la taille des données ASUP, de la taille du cluster mise à l'échelle, et si le délai de collecte dépasse la limite de sept jours.



== La désinstallation d'Astra Control Center ne parvient pas à nettoyer le module de l'opérateur de surveillance sur le cluster géré

Si vous n'avez pas dégéré les clusters avant de désinstaller Astra Control Center, vous pouvez supprimer manuellement les pods dans l'espace de noms netapp-Monitoring et dans l'espace de noms à l'aide des commandes suivantes :

.Étapes
. Supprimer `acc-monitoring` agent :
+
[listing]
----
oc delete agents acc-monitoring -n netapp-monitoring
----
+
Résultat :

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Supprimez le namespace :
+
[listing]
----
oc delete ns netapp-monitoring
----
+
Résultat :

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Confirmer la suppression des ressources :
+
[listing]
----
oc get pods -n netapp-monitoring
----
+
Résultat :

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Confirmer la suppression de l'agent de surveillance :
+
[listing]
----
oc get crd|grep agent
----
+
Résultat de l'échantillon :

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Supprimer les informations de définition de ressource personnalisée (CRD) :
+
[listing]
----
oc delete crds agents.monitoring.netapp.com
----
+
Résultat :

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




== La désinstallation d'Astra Control Center ne parvient pas à nettoyer les CRD Traefik

Vous pouvez supprimer manuellement les CRD Traefik :

.Étapes
. Confirmez les CRD qui n'ont pas été supprimés par le processus de désinstallation :
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Réponse

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Supprimez les CRD :
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us
----




== Collecte ASUP bloquée en état de génération ou de chargement

Si un pod ASUP est arrêté ou redémarré, il est possible que la collecte ASUP soit bloquée en état de génération ou de téléchargement. Effectuez les opérations suivantes link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["API REST Astra Control"] appeler pour lancer à nouveau la collecte manuelle :

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /Accounts/{AccountID}/core/v1/asups 
|===

NOTE: Cette solution de contournement de l'API fonctionne uniquement si la procédure est effectuée plus de 10 minutes après le démarrage d'ASUP.



== Trouvez plus d'informations

* link:../release-notes/known-limitations.html["Restrictions connues pour cette version"]

